<?php $desktop_layout_footer=array (
  'rows' => 
  array (
    0 => 
     array(
       'id' => 'footer',
       'child' => 
      array (
        0 => 
         array(
           'id' => 'row1',
           'type' => 'box',
           'child' => 
          array (
            0 => 
             array(
               'type' => 'html',
               'tag' => 'img',
               'id' => 'row1-img1',
            ),
          ),
        ),
        1 => 
         array(
           'id' => 'row2',
           'type' => 'box',
           'child' => 
          array (
            0 => 
             array(
               'type' => 'html',
               'tag' => 'p',
               'id' => 'row2-p1',
            ),
          ),
        ),
        2 => 
         array(
           'id' => 'row3',
           'type' => 'box',
           'child' => 
          array (
            0 => 
             array(
               'type' => 'html',
               'tag' => 'card',
               'id' => 'row3-card1',
            ),
            1 => 
             array(
               'type' => 'html',
               'tag' => 'card',
               'id' => 'row3-card2',
            ),
            2 => 
             array(
               'type' => 'html',
               'tag' => 'card',
               'id' => 'row3-card3',
            ),
            3 => 
             array(
               'type' => 'html',
               'tag' => 'card',
               'id' => 'row3-card4',
            ),
            4 => 
             array(
               'type' => 'html',
               'tag' => 'card',
               'id' => 'row3-card5',
            ),
          ),
        ),
        3 => 
         array(
           'id' => 'row5',
           'type' => 'box',
           'child' => 
          array (
          ),
        ),
        4 => 
         array(
           'id' => 'row4',
           'type' => 'box',
           'child' => 
          array (
            0 => 
             array(
               'id' => 'row4_box1',
               'type' => 'box',
               'child' => 
              array (
                0 => 
                 array(
                   'type' => 'html',
                   'tag' => 'ul',
                   'id' => 'row4_box1-ul1',
                ),
              ),
            ),
            1 => 
             array(
               'id' => 'row4_box2',
               'type' => 'box',
               'child' => 
              array (
                0 => 
                 array(
                   'type' => 'html',
                   'tag' => 'ul',
                   'id' => 'row4_box2-ul2',
                ),
              ),
            ),
            2 => 
             array(
               'id' => 'row4_box3',
               'type' => 'box',
               'child' => 
              array (
                0 => 
                 array(
                   'type' => 'html',
                   'tag' => 'ul',
                   'id' => 'row4_box3-ul3',
                ),
              ),
            ),
            3 => 
             array(
               'id' => 'row4_box4',
               'type' => 'box',
               'child' => 
              array (
                0 => 
                 array(
                   'type' => 'html',
                   'tag' => 'p',
                   'id' => 'row4_box4-p2',
                ),
                1 => 
                 array(
                   'type' => 'html',
                   'tag' => 'img',
                   'id' => 'row4_box4-img5',
                ),
                2 => 
                 array(
                   'type' => 'html',
                   'tag' => 'img',
                   'id' => 'row4_box4-img6',
                ),
                3 => 
                 array(
                   'type' => 'html',
                   'tag' => 'img',
                   'id' => 'row4_box4-img13',
                ),
                4 => 
                 array(
                   'type' => 'html',
                   'tag' => 'img',
                   'id' => 'row4_box4-img14',
                ),
              ),
            ),
          ),
        ),
        5 => 
         array(
           'id' => 'row6',
           'type' => 'box',
           'child' => 
          array (
            0 => 
             array(
               'id' => 'row6_box1',
               'type' => 'box',
               'child' => 
              array (
                0 => 
                 array(
                   'type' => 'html',
                   'tag' => 'p',
                   'id' => 'row6_box1-p3',
                ),
              ),
            ),
            1 => 
             array(
               'id' => 'row6_box2',
               'type' => 'box',
               'child' => 
              array (
                0 => 
                 array(
                   'type' => 'html',
                   'tag' => 'img',
                   'id' => 'row6_box2-img15',
                ),
                1 => 
                 array(
                   'type' => 'html',
                   'tag' => 'img',
                   'id' => 'row6_box2-img16',
                ),
              ),
            ),
          ),
        ),
        6 => 
         array(
           'id' => 'row7',
           'type' => 'box',
           'child' => 
          array (
            0 => 
             array(
               'id' => 'row7_box1',
               'type' => 'box',
               'child' => 
              array (
                0 => 
                 array(
                   'type' => 'html',
                   'tag' => 'p',
                   'id' => 'row7_box1-p4',
                ),
                1 => 
                 array(
                   'type' => 'html',
                   'tag' => 'p',
                   'id' => 'row7_box1-p5',
                ),
              ),
            ),
            1 => 
             array(
               'type' => 'html',
               'tag' => 'code',
               'id' => 'row7-code3',
            ),
            2 => 
             array(
               'type' => 'html',
               'tag' => 'code',
               'id' => 'row7-code4',
            ),
          ),
        ),
        7 => 
         array(
           'id' => 'row8',
           'type' => 'box',
           'child' => 
          array (
          ),
        ),
        8 => 
         array(
           'id' => 'row9',
           'type' => 'box',
           'child' => 
          array (
            0 => 
             array(
               'type' => 'html',
               'tag' => 'p',
               'id' => 'row9-p6',
            ),
          ),
        ),
      ),
    ),
  ),
  'style' => 
   array(
     'row7-code4' => 
     array(
       'width' => '',
       'height' => '',
       'backgroundColor' => '',
       'color' => '',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'row7-code3' => 
     array(
       'width' => '',
       'height' => '',
       'backgroundColor' => '',
       'color' => '',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'row7_box2-code2' => 
    array (
    ),
     'row7_box2-code1' => 
    array (
    ),
     'row9-p6' => 
     array(
       'width' => 'auto',
       'height' => '',
       'backgroundColor' => '',
       'color' => '#757575FF',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'column',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'center',
       'justifyContent' => 'space-between',
    ),
     'row9' => 
     array(
       'width' => '97%',
       'height' => 'auto',
       'backgroundColor' => 'transparent',
       'color' => '',
       'marginTop' => '20px',
       'marginRight' => 'auto',
       'marginLeft' => 'auto',
       'marginBottom' => '10px',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'column',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'center',
       'justifyContent' => 'space-between',
    ),
     'row8' => 
     array(
       'width' => '97%',
       'height' => '1px',
       'backgroundColor' => '#E0E0E0FF',
       'color' => '',
       'marginTop' => '',
       'marginRight' => 'auto',
       'marginLeft' => 'auto',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'column',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'row7_box1-p5' => 
     array(
       'width' => '',
       'height' => '',
       'backgroundColor' => '',
       'color' => '#757575FF',
       'marginTop' => '10px',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '10px',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'row7_box1-p4' => 
     array(
       'width' => '',
       'height' => '',
       'backgroundColor' => '',
       'color' => '#000000FF',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'row7_box1' => 
     array(
       'width' => '65%',
       'height' => 'auto',
       'backgroundColor' => '',
       'color' => '#FF0000FF',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '#FF0000FF',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'column',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'row7' => 
     array(
       'width' => '97%',
       'height' => 'auto',
       'backgroundColor' => 'transparent',
       'color' => '#00000000',
       'marginTop' => '20px',
       'marginRight' => 'auto',
       'marginLeft' => 'auto',
       'marginBottom' => '20px',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '#FFFFFFFF',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'row6_box2-img16' => 
     array(
       'width' => '120px',
       'height' => '',
       'backgroundColor' => '#00000000',
       'color' => '#00000000',
       'marginTop' => '10px',
       'marginRight' => '',
       'marginLeft' => '10px',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'row6_box2-img15' => 
     array(
       'width' => '120px',
       'height' => '',
       'backgroundColor' => '#00000000',
       'color' => '#00000000',
       'marginTop' => '10px',
       'marginRight' => '',
       'marginLeft' => '10px',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'row6_box1-p3' => 
     array(
       'width' => '',
       'height' => '',
       'backgroundColor' => '#00000000',
       'color' => '#FFFFFFFF',
       'marginTop' => '10px',
       'marginRight' => '10px',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'row6_box2' => 
     array(
       'width' => '100%',
       'height' => 'auto',
       'backgroundColor' => '#00000000',
       'color' => '#00000000',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'end',
    ),
     'row6_box1' => 
     array(
       'width' => '100%',
       'height' => 'auto',
       'backgroundColor' => '',
       'color' => '',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'column',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'row6' => 
     array(
       'width' => '97%',
       'height' => 'auto',
       'backgroundColor' => '#1A237EFF',
       'color' => '',
       'marginTop' => '20px',
       'marginRight' => 'auto',
       'marginLeft' => 'auto',
       'marginBottom' => '20px',
       'paddingTop' => '20px',
       'paddingRight' => '10px',
       'paddingLeft' => '10px',
       'paddingBottom' => '20px',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '10px',
       'borderBottomLeftRadius' => '10px',
       'borderBottomRightRadius' => '10px',
       'borderTopLeftRadius' => '10px',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'space-between',
    ),
     'row4_box4-img14' => 
     array(
       'width' => '',
       'height' => '',
       'backgroundColor' => '',
       'color' => '',
       'marginTop' => '30px',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'row4_box4-img13' => 
     array(
       'width' => '',
       'height' => '',
       'backgroundColor' => '',
       'color' => '',
       'marginTop' => '30px',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'row4_box4-img6' => 
     array(
       'width' => '',
       'height' => '',
       'backgroundColor' => '',
       'color' => '',
       'marginTop' => '30px',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'row4_box4-img5' => 
     array(
       'width' => '',
       'height' => '',
       'backgroundColor' => '',
       'color' => '#00000000',
       'marginTop' => '32px',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'row4_box4-p2' => 
     array(
       'width' => '',
       'height' => '',
       'backgroundColor' => '',
       'color' => '#000000FF',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'row4_box3-ul3' => 
     array(
       'width' => '',
       'height' => '',
       'backgroundColor' => '#00000000',
       'color' => '#757575FF',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'column',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'row4_box2-ul2' => 
     array(
       'width' => '',
       'height' => '',
       'backgroundColor' => '#00000000',
       'color' => '#757575FF',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'column',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'row5' => 
     array(
       'width' => '97%',
       'height' => '1px',
       'backgroundColor' => '#E0E0E0FF',
       'color' => '',
       'marginTop' => '10px',
       'marginRight' => 'auto',
       'marginLeft' => 'auto',
       'marginBottom' => '10px',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'column',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'row4_box1-ul1' => 
     array(
       'width' => '',
       'height' => '',
       'backgroundColor' => '',
       'color' => '#757575FF',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'column',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'row4_box4' => 
     array(
       'width' => '100%',
       'height' => '100px',
       'backgroundColor' => '',
       'color' => '',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'row4_box3' => 
     array(
       'width' => '100%',
       'height' => 'auto',
       'backgroundColor' => '#00000000',
       'color' => '#757575FF',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'column',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'row4_box2' => 
     array(
       'width' => '100%',
       'height' => 'auto',
       'backgroundColor' => '#00000000',
       'color' => '#BDBDBDFF',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'column',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'row4_box1' => 
     array(
       'width' => '100%',
       'height' => 'auto',
       'backgroundColor' => '',
       'color' => '',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'column',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'row4' => 
     array(
       'width' => '97%',
       'height' => 'auto',
       'backgroundColor' => '',
       'color' => '',
       'marginTop' => '',
       'marginRight' => 'auto',
       'marginLeft' => 'auto',
       'marginBottom' => '',
       'paddingTop' => '10px',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '10px',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'row3-card5' => 
     array(
       'width' => '100%',
       'height' => '',
       'backgroundColor' => '',
       'color' => '',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'column',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'center',
       'justifyContent' => 'start',
    ),
     'row3-card4' => 
     array(
       'width' => '100%',
       'height' => '',
       'backgroundColor' => '',
       'color' => '',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'column',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'center',
       'justifyContent' => 'start',
    ),
     'row3-card3' => 
     array(
       'width' => '100%',
       'height' => '',
       'backgroundColor' => '',
       'color' => '',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'column',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'center',
       'justifyContent' => 'start',
    ),
     'row3-card2' => 
     array(
       'width' => '100%',
       'height' => '',
       'backgroundColor' => '',
       'color' => '',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'column',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'center',
       'justifyContent' => 'start',
    ),
     'row3-card1' => 
     array(
       'width' => '100%',
       'height' => '',
       'backgroundColor' => '',
       'color' => '',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'column',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'center',
       'justifyContent' => 'start',
    ),
     'row3' => 
     array(
       'width' => '85%',
       'height' => 'auto',
       'backgroundColor' => '',
       'color' => '',
       'marginTop' => '20px',
       'marginRight' => 'auto',
       'marginLeft' => 'auto',
       'marginBottom' => '20px',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'space-between',
    ),
     'row2-p1' => 
     array(
       'width' => '',
       'height' => '',
       'backgroundColor' => '#00000000',
       'color' => '',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'row2' => 
     array(
       'width' => '100%',
       'height' => '40px',
       'display' => 'flex',
       'flexDirection' => 'column',
    ),
     'row1-img1' => 
     array(
       'width' => '100px',
       'height' => '',
       'backgroundColor' => '#00000000',
       'color' => '',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'row1' => 
     array(
       'width' => '100%',
       'height' => 'auto',
       'backgroundColor' => '#00000000',
       'color' => '',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'column',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'footer' => 
     array(
       'width' => '100%',
       'height' => 'auto',
       'backgroundColor' => '#FFFFFFFF',
       'color' => '',
       'marginTop' => '50px',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '20px',
       'paddingRight' => '30px',
       'paddingLeft' => '30px',
       'paddingBottom' => '20px',
       'borderWidth' => '1px',
       'borderColor' => '#F5F5F5FF',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'column',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
  ),
  'tags' => 
   array(
     'horizontal_product_list' => 
    array (
    ),
     'slider' => 
    array (
    ),
     'incredibleOffers' => 
    array (
    ),
     'posts' => 
    array (
    ),
     'img' => 
     array(
       'row6_box2-img16' => 
       array(
         'src' => 'https://teraket.com/files/images/b43d144f.svg',
         'link' => '',
         'hoverSrc' => '',
      ),
       'row6_box2-img15' => 
       array(
         'src' => 'https://teraket.com/files/images/6f0c9aeb.svg',
         'link' => '',
         'hoverSrc' => '',
      ),
       'row4_box4-img14' => 
       array(
         'src' => 'https://teraket.com/files/images/1628236560.svg',
         'link' => '',
         'hoverSrc' => '',
      ),
       'row4_box4-img13' => 
       array(
         'src' => 'https://teraket.com/files/images/1628234416.svg',
         'link' => '',
         'hoverSrc' => '',
      ),
       'row4_box4-img6' => 
       array(
         'src' => 'https://teraket.com/files/images/1628234431.svg',
         'link' => '',
         'hoverSrc' => '',
      ),
       'row4_box4-img5' => 
       array(
         'src' => 'https://teraket.com/files/images/1628234408.svg',
         'link' => '',
         'hoverSrc' => '',
      ),
       'row1-img1' => 
       array(
         'src' => 'https://teraket.com/files/images/1639914521.png',
         'link' => 'https://teraket.com/',
         'hoverSrc' => '',
      ),
    ),
     'card' => 
     array(
       'row3-card5' => 
       array(
         'title' => 'ضمانت اصل بودن کالا',
         'content' => '',
         'img' => 'https://teraket.com/files/images/fdb293e6.svg',
         'titleColor' => '',
         'titlePadding' => '',
         'titleSize' => '14px',
         'contentPadding' => '',
         'contentSize' => '',
         'link' => '',
         'icon' => '',
         'iconColor' => '',
         'imgWidth' => '64px',
         'imageMargin' => 'auto',
      ),
       'row3-card4' => 
       array(
         'title' => '10 روز ضمانت بازگشت کالا',
         'content' => '',
         'img' => 'https://teraket.com/files/images/514926b1.svg',
         'titleColor' => '',
         'titlePadding' => '',
         'titleSize' => '14px',
         'contentPadding' => '',
         'contentSize' => '',
         'link' => '',
         'icon' => '',
         'iconColor' => '',
         'imgWidth' => '64px',
         'imageMargin' => 'auto',
      ),
       'row3-card3' => 
       array(
         'title' => '۷ روز هفته، ۲۴ ساعته',
         'content' => '',
         'img' => 'https://teraket.com/files/images/a9286d2f.svg',
         'titleColor' => '',
         'titlePadding' => '',
         'titleSize' => '14px',
         'contentPadding' => '',
         'contentSize' => '',
         'link' => '',
         'icon' => '',
         'iconColor' => '',
         'imgWidth' => '66px',
         'imageMargin' => 'auto',
      ),
       'row3-card2' => 
       array(
         'title' => 'پرداخت امن',
         'content' => '',
         'img' => 'https://teraket.com/files/images/22414818.svg',
         'titleColor' => '',
         'titlePadding' => '',
         'titleSize' => '14px',
         'contentPadding' => '',
         'contentSize' => '',
         'link' => '',
         'icon' => '',
         'iconColor' => '',
         'imgWidth' => '66px',
         'imageMargin' => 'auto',
      ),
       'row3-card1' => 
       array(
         'title' => 'ضمانت اصل بودن کالا',
         'content' => '',
         'img' => 'https://teraket.com/files/images/fdb293e6.svg',
         'titleColor' => '',
         'titlePadding' => '',
         'titleSize' => '14px',
         'contentPadding' => '',
         'contentSize' => '',
         'link' => '',
         'icon' => '',
         'iconColor' => '',
         'imgWidth' => '64px',
         'imageMargin' => 'auto',
      ),
    ),
     'ul' => 
     array(
       'row4_box3-ul3' => 
       array(
         'title' => 'راهنمای خرید از تراکت',
         'titleColor' => '#000000FF',
         'titleSize' => '18px',
         'titleIcon' => '',
         'items' => 
        array (
          0 => 
           array(
             'title' => 'نحوه ثبت سفارش',
             'link' => '',
          ),
          1 => 
           array(
             'title' => 'رویه ارسال سفارش',
             'link' => '',
          ),
          2 => 
           array(
             'title' => 'شیوه‌های پرداخت',
             'link' => '',
          ),
        ),
         'itemPadding' => '5px 5px 5px 0px',
         'hoverColor' => '#03A9F4FF',
      ),
       'row4_box2-ul2' => 
       array(
         'title' => 'خدمات مشتریان',
         'titleColor' => '#000000FF',
         'titleSize' => '18px',
         'titleIcon' => '',
         'items' => 
        array (
          0 => 
           array(
             'title' => 'پاسخ به پرسش‌های متداول',
             'link' => '',
          ),
          1 => 
           array(
             'title' => 'رویه‌های بازگرداندن کالا',
             'link' => '',
          ),
          2 => 
           array(
             'title' => 'شرایط استفاده',
             'link' => '',
          ),
          3 => 
           array(
             'title' => 'حریم خصوصی',
             'link' => '',
          ),
        ),
         'itemPadding' => '5px 5px 5px 0px',
         'hoverColor' => '#03A9F4FF',
      ),
       'row4_box1-ul1' => 
       array(
         'title' => 'با تراکت',
         'titleColor' => '#000000FF',
         'titleSize' => '18px',
         'titleIcon' => '',
         'items' => 
        array (
          0 => 
           array(
             'title' => 'فروش در تراکت',
             'link' => '',
          ),
          1 => 
           array(
             'title' => 'تماس با تراکت',
             'link' => '',
          ),
          2 => 
           array(
             'title' => 'درباره تراکت',
             'link' => '',
          ),
        ),
         'itemPadding' => '5px 5px 5px 0px',
         'hoverColor' => '#03A9F4FF',
      ),
    ),
     'code' => 
     array(
       'row7-code4' => 
       array(
         'content' => '<a referrerpolicy="origin" target="_blank" href="https://trustseal.enamad.ir/?id=215164&amp;Code=wFRs8HXwQnB6Ljfu7Tcy"><img referrerpolicy="origin" src="https://Trustseal.eNamad.ir/logo.aspx?id=215164&amp;Code=wFRs8HXwQnB6Ljfu7Tcy" alt="" style="cursor:pointer" id="wFRs8HXwQnB6Ljfu7Tcy"></a>
',
      ),
       'row7-code3' => 
       array(
         'content' => '<img referrerpolicy=\'origin\' id = \'nbqejzpejzpewlaonbqeoeuk\' style = \'cursor:pointer\' onclick = \'window.open("https://logo.samandehi.ir/Verify.aspx?id=277428&p=uiwkjyoejyoeaodsuiwkmcsi", "Popup","toolbar=no, scrollbars=no, location=no, statusbar=no, menubar=no, resizable=0, width=450, height=630, top=30")\' alt = \'logo-samandehi\' src = \'https://logo.samandehi.ir/logo.aspx?id=277428&p=odrfyndtyndtshwlodrfaqgw\' />',
      ),
       'row7_box2-code2' => 
       array(
         'content' => '',
      ),
       'row7_box2-code1' => 
       array(
         'content' => '',
      ),
    ),
     'p' => 
     array(
       'row9-p6' => 
       array(
         'content' => ' استفاده از مطالب فروشگاه اینترنتی تراکت فقط برای مقاصد غیرتجاری و با ذکر منبع بلامانع است. کلیه حقوق این سایت متعلق به تراکت می‌باشد.
',
         'showMore' => '',
      ),
       'row7_box1-p5' => 
       array(
         'content' => 'توضیحات فروشگاه',
         'showMore' => '',
      ),
       'row7_box1-p4' => 
       array(
         'content' => 'فروشگاه اینترنتی تراکت به عنوان بازار آنلاین شهر در کنار شماست.',
         'showMore' => '',
      ),
       'row6_box1-p3' => 
       array(
         'content' => 'دانلود اپلیکیشن تراکت (به زودی...)',
         'showMore' => '',
      ),
       'row4_box4-p2' => 
       array(
         'content' => ' با ما همراه باشید',
         'showMore' => '',
      ),
       'row2-p1' => 
       array(
         'content' => 'تلفن پشتیبانی:
09184466448 | هفت روز هفته، ۲۴ ساعت شبانه‌روز پاسخگوی شما هستیم.',
         'showMore' => '',
      ),
    ),
     'slide' => 
    array (
    ),
  ),
  'responsive_style' => 
   array(
     'min_row7_box2-code2_902' => 
     array(
       'width' => '150px',
       'height' => '150px',
       'type' => 'min',
    ),
  ),
)?>