<?php


namespace Modules\incredibleOffers\Http\Requests;


use App\Http\Requests\CFormRequest;

class OffersRequest extends CFormRequest
{
    public function authorize(){
        return true;
    }

    public function rules()
    {
        return [
            'price1'=>'required|numeric',
            'price2'=>'required|numeric',
            'product_number'=>'required|numeric',
            'product_number_cart'=>'required|numeric',
            'date1'=>'required',
            'date2'=>'required'
        ];
    }

    public function attributes(){
        return [
            'price1'=>'قیمت محصول',
            'price2'=>'قیمت محصول برای فروش',
            'product_number'=>'تعداد موجودی محصول',
            'product_number_cart'=>'تعداد سفارش در سبد خرید',
            'date1'=>'تاریخ شروع',
            'date2'=>'تاریخ پایان'
        ];
    }

    protected function getValidatorInstance()
    {
        $data=$this->request->all();
        foreach ($data as $key=>$value){
            if(is_string($value)){
                $e=explode($value,',');
                if(sizeof($e)>=0){
                    $this->merge([
                        $key=>str_replace(',','',$this->request->get($key))
                    ]);
                }
            }
        }
        return parent::getValidatorInstance(); // TODO: Change the autogenerated stub
    }
}

