<?php

namespace Modules\discount\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class DiscountRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        $rules=[
            'code'=>'required',
            'expiry_time'=>'required',
        ];
        if(empty($this->amount_discount) && empty($this->amount_percent)){
            $rules['amount_discount']='required';
        }
        return $rules;
    }
    public function attributes()
    {
        return [
            'code'=>'کد تخفیف',
            'expiry_time'=>'تاریخ انقضا',
            'amount_discount'=>'میزان کد تخفیف (بر حسب تومان)'
        ];
    }
    protected function getValidatorInstance()
    {
        if($this->request->has('amount'))
        {
            $this->merge([
                'amount'=>str_replace(',','',$this->request->get('amount'))
            ]);
        }
        if($this->request->has('number_usable'))
        {
            $this->merge([
                'number_usable'=>str_replace(',','',$this->request->get('number_usable'))
            ]);
        }
        if($this->request->has('amount_discount'))
        {
            $this->merge([
                'amount_discount'=>str_replace(',','',$this->request->get('amount_discount'))
            ]);
        }
        if($this->request->has('amount_percent'))
        {
            $this->merge([
                'amount_percent'=>str_replace(',','',$this->request->get('amount_percent'))
            ]);
        }

        return parent::getValidatorInstance(); // TODO: Change the autogenerated stub
    }
}
